In [ ]:
# This notobook is for Representation alignment tests for text-type data

!pip install sentence-transformers
!pip -qqq install bitsandbytes accelerate
!pip install git+https://github.com/huggingface/accelerate
!pip install accelarate
from sentence_transformers import SentenceTransformer, util

from astropy.io import fits
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity


from transformers import AutoModelForCausalLM
from transformers import AutoTokenizer


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 13.9 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=9a5c4ebae1de452410ffc69b8cb01966949c4eed4dced86efa0ed19ab0130ecd
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence-transformers
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.0/105.0 MB 9.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 270.9/270.9 kB 28.8 MB/s eta 0:00:00
  Cloning https://github.com/huggingface/accelerate to /tmp/pip-req-build-xiebx6e2
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/accelerate /tmp/pip-req-build-xiebx6e2
  Resolved https://github.com/huggingface/accelerate to commit 31fd2b1ad6b9c1cd1480568399a311b3caa

In [ ]:
# Import data for ULX and YSO proposals

ULX = pd.read_csv('ULX.csv')
YSO = pd.read_csv('YSO.csv')

print(type(ULX['Proposal']))

<class 'pandas.core.series.Series'>


In [ ]:
# Attemp_1 with SentenceTransformer

model_SentenceTransformer = SentenceTransformer('all-MiniLM-L12-v2')

def create_embeddings_with_sentenceTransformer(proposals):
    embeddings = []
    for proposal in proposals:
        embeddings.append(model_SentenceTransformer.encode(proposal, convert_to_tensor=True));
    return embeddings


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


.gitattributes:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/573 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

data_config.json:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/134M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/352 [00:00<?, ?B/s]

train_script.py:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [ ]:
embeddings_ULX_sentenceTransformer = create_embeddings_with_sentenceTransformer(ULX['Proposal']);
embeddings_YSO_sentenceTransformer = create_embeddings_with_sentenceTransformer(YSO['Proposal']);

In [ ]:
embeddings_ULX_sentenceTransformer_keywords = create_embeddings_with_sentenceTransformer(ULX['Keywords']);
embeddings_YSO_sentenceTransformer_keywords = create_embeddings_with_sentenceTransformer(YSO['Keywords']);

In [ ]:
embeddings_ULX_sentenceTransformer_keywords15 = create_embeddings_with_sentenceTransformer(ULX['Keywords15']);
embeddings_YSO_sentenceTransformer_keywords15 = create_embeddings_with_sentenceTransformer(YSO['Keywords15']);

In [ ]:
embeddings_ULX_sentenceTransformer_keywords25 = create_embeddings_with_sentenceTransformer(ULX['keywords25']);
embeddings_YSO_sentenceTransformer_keywords25 = create_embeddings_with_sentenceTransformer(YSO['Keywords25']);

In [ ]:
# Reshape the arrays to match the expected input shape of cosine_similarity
# possibly not required / commented for now

# for embedding in embeddings_ULX:
#   for word in embedding:
#     word = word.reshape(1, -1)

# for embedding in embeddings_YSO:
#   for word in embedding:
#     word = word.reshape(1, -1)

In [ ]:
#Compute cosine-similarities for each keyword collection with every paragraph

def find_keyword_cos_sim(embeddingKeywords, embeddingParagraphs):
  results = []
  for i in range (0,len(embeddingParagraphs)-1):
      results.append(util.cos_sim(embeddingKeywords, embeddingParagraphs[i]))
  return results

In [ ]:
a = find_keyword_cos_sim(embeddings_ULX_sentenceTransformer_keywords[1],embeddings_ULX_sentenceTransformer)
b = find_keyword_cos_sim(embeddings_ULX_sentenceTransformer_keywords15[1],embeddings_ULX_sentenceTransformer)
c = find_keyword_cos_sim(embeddings_ULX_sentenceTransformer_keywords25[1],embeddings_ULX_sentenceTransformer)

In [ ]:
for i in range (0, len(embeddings_ULX_sentenceTransformer)):
  a = find_keyword_cos_sim(embeddings_ULX_sentenceTransformer_keywords15[i],embeddings_ULX_sentenceTransformer);
  print(max(a))



tensor([[0.8618]])
tensor([[0.8370]])
tensor([[0.9164]])
tensor([[0.8334]])
tensor([[0.8548]])
tensor([[0.7594]])
tensor([[0.8571]])
tensor([[0.8752]])
tensor([[0.8304]])
tensor([[0.5338]])


In [ ]:
for i in range (0, len(embeddings_ULX_sentenceTransformer)):
  a = find_keyword_cos_sim(embeddings_YSO_sentenceTransformer_keywords15[i],embeddings_YSO_sentenceTransformer);
  print(max(a))

tensor([[0.8099]])
tensor([[0.8792]])
tensor([[0.8623]])
tensor([[0.8517]])
tensor([[0.8393]])
tensor([[0.7806]])
tensor([[0.8883]])
tensor([[0.8876]])
tensor([[0.8666]])
tensor([[0.6866]])


In [ ]:
max(c)

tensor([[0.8186]])

In [ ]:
#Compute cosine-similarities for each sentence with each other sentence

def find_average_cos_sim(embeddings1, embedding2):
  num = 0
  cosine_scores = 0
  for i in range (0,len(embeddings1)-1):
    for j in range (0,len(embedding2)-1):
      cosine_scores += util.cos_sim(embeddings1[i], embedding2[j])
      num+=1
  return cosine_scores/num

In [ ]:
# ULX/YSO
find_average_cos_sim(embeddings_ULX_sentenceTransformer,embeddings_YSO_sentenceTransformer)

tensor([[0.5218]])

In [ ]:
# ULX/ULX
find_average_cos_sim(embeddings_ULX_sentenceTransformer,embeddings_ULX_sentenceTransformer)

tensor([[0.6157]])

In [ ]:
# YSO/YSO
find_average_cos_sim(embeddings_YSO_sentenceTransformer,embeddings_YSO_sentenceTransformer)

tensor([[0.6211]])

In [ ]:
# ULX/YSO
find_average_cos_sim(embeddings_YSO_sentenceTransformer_keywords,embeddings_YSO_sentenceTransformer)

tensor([[0.5677]])

In [ ]:
# ULX/YSO
find_average_cos_sim(embeddings_YSO_sentenceTransformer_keywords,embeddings_ULX_sentenceTransformer)

tensor([[0.4763]])

In [ ]:
# Attemp_2 with astrollama
!pip install accelerate

tokenizer = AutoTokenizer.from_pretrained(
    pretrained_model_name_or_path="universeTBD/astrollama"
)

model_astrollama = AutoModelForCausalLM.from_pretrained(
    pretrained_model_name_or_path="universeTBD/astrollama"
)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:72: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/698 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/21.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/438 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:72: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/9.88G [00:00<?, ?B/s]

KeyboardInterrupt: 

In [ ]:
def create_embeddings_with_astrollama(proposals):
    embeddings = []
    proposals.to_dict();
    for proposal in proposals:
        print(proposal)
        inputs = tokenizer(
            proposal,
            return_tensors="pt",
            return_token_type_ids=False,
            padding=True,
            truncation=True,
            max_length=4096
        )
        inputs.to(model_astrollama.device)
        outputs = model_astrollama(**inputs, output_hidden_states=True)

        # Last layer of the hidden states. Get average embedding of all tokens
        embedding = outputs["hidden_states"][-1][:, 1:, ...].mean(1).detach().cpu().numpy()
        embeddings.append(embedding)
    return embeddings


In [ ]:
ULX_embeddings_astrollama = create_embeddings_with_astrollama(ULX['Proposal'])
YSO_embeddings_astrollama = create_embeddings_with_astrollama(YSO['Proposal'])

In [ ]:
# ULX/ULX
find_average_cos_sim(ULX_embeddings_astrollama,ULX_embeddings_astrollama)

# ULX/YSO
find_average_cos_sim(ULX_embeddings_astrollama,YSO_embeddings_astrollama)

# YSO/YSO
find_average_cos_sim(YSO_embeddings_astrollama,YSO_embeddings_astrollama)

In [ ]:
# For every keywords fins cos sim with all other paragraphs ...


